version: '3'
services:

  deakin-catalog:
    image: deakin-catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: deakin-catalog
    ports:
     - "4000:4000"
    environment:
      - PORT=4000
      - DATABASE_URL=postgresql://part_4_user:crI1oRDLcEzac8cTnWHWUCe3whzza8dZ@dpg-crghtuqj1k6c739i4lhg-a.oregon-postgres.render.com/part_4
    restart: "no"

  deakin-inventory:
    image: deakin-inventory
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: deakin-inventory
    ports:
     - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://part_4_user:crI1oRDLcEzac8cTnWHWUCe3whzza8dZ@dpg-crghtuqj1k6c739i4lhg-a.oregon-postgres.render.com/part_4
    restart: "no"